### ISSUE TITLE
importMeta() failing with source = "aurn" 

### ISSUE THREAD

**Issue by cvitolo** [davidcarslaw/openair#65]
Hi David,

I'm trying to  run 
    x <- importMeta(source='aurn', all = TRUE)

but I get the following error
    Error in load(con) : cannot open the connection

The same function works fine with source = "kcl" or source = "saqn".

Maybe the file permission changed on the server side? 
Is there any workaround this issue?

Many thanks,
Claudia

**Comment by davidcarslaw** [comment]
Thanks Claudia. Yes, I think the server side format has changed. Should be fixed now. Note also in the help file to `importAURN` that there is more up to date meta data included (more sites but not all meta fields). I Need to requery the data used for `importMeta`, which I will look at now...

**Comment by iamack** [comment]
Hi,
I'm still seeing the same issue described by Claudia. Also importAURN fails while importKCL works okay. Can you please confirm if the problem should be fixed.
Regards,
Ian

**Comment by davidcarslaw** [comment]
I have modified the code - so hopefully it works now. I think the problem is due to new meta data being made available. It should now be kept up to date. Let me know if you still have a problem...

Thanks

**Comment by iamack** [comment]
Thanks for looking at this, but I'm still seeing the same problem. I'm running R at the command line under linux. I issue the commands
library(openair)
x <- importMeta(source='aurn', all = TRUE)

and get
Error in load(con) : cannot open the connection

while
x <- importMeta(source='kcl', all = TRUE) 
completes with no error.

library(help = openair) 
returns

Package:            openair
Type:               Package
Title:              Tools for the Analysis of Air Pollution Data
Version:            1.1-0
Date:               2015-01-05
Authors@R:          c(person("David", "Carslaw", role = c("aut",
                    "cre"), email = "david.carslaw@kcl.ac.uk"),
                    person("Karl", "Ropkins", role = "aut", email =
                    "K.Ropkins@its.leeds.ac.uk"))
ByteCompile:        true
Depends:            R (>= 2.15.1), maps,
Imports:            utils, grid, plyr, reshape2, mgcv, lattice,
                    latticeExtra, cluster, RColorBrewer, mapdata,
                    mapproj, hexbin, RgoogleMaps, Rcpp
Suggests:           png, KernSmooth
LinkingTo:          Rcpp
Maintainer:         David Carslaw <david.carslaw@kcl.ac.uk>

Regards
Ian

**Comment by davidcarslaw** [comment]
Hopefully this should be fixed - due I think to change to https on server...

**Comment by esofian** [comment]
Dear David,

I'm trying to import metadata for aurn using:
meta <- importMeta(source='aurn', all = TRUE)

However, I get the error message:
Error in load(con) : cannot open the connection

The same function works for "kcl" or "saqn". I noticed that this issue for "aurn" has been also reported in the past and you resolved it. I wonder if you could help me with this.

Thank you
Eleni

**Comment by davidcarslaw** [comment]
Thanks Eleni. I can't reproduce this on my machines (all with R 3.4.0 and openair 2.1-0). I've tested on Windows 7, 10, ubuntu and Mac OS. What version of R/openair are you using?

**Comment by esofian** [comment]
Thank you for looking at this. Yes, I will update my R studio to work with the most recent openair 2.1-0 version.
Kind Regards
Eleni
